### ISSUE TITLE
CLI doesnt work

### ISSUE THREAD

**Issue by Sendoo** [lnquy065/super-lang-editor#1]
Hi!
Step after select JSON Format, doesnt work.
File selection doesn't work, nothing happens on click.
![изображение](https://user-images.githubusercontent.com/46229254/68131486-d4c40600-ff25-11e9-803f-c4108048bec4.png)

OS: Windows 10 x64 1903
Node: 12.13.0 LTS

**Comment by Sendoo** [comment]
No, files are not scanned (

**Comment by lnquy065** [comment]
Can you show me name of those files?

**Comment by Sendoo** [comment]
![изображение](https://user-images.githubusercontent.com/46229254/68133132-86643680-ff28-11e9-956d-e0a1f851a9ec.png)

**Comment by lnquy065** [comment]
At current version (v1.4), SLE only scans files that have name follow ISO 639-1 standard :(
https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes
I'll add more options for scanning all *.json files on next version.
Thanks for feedback

**Comment by lnquy065** [comment]
Hi bro,
I'm just release a patch version 1.4.1, now it can scan all json file!
